title: Pravin Regismond
logo: /assets/img/headshot_circle.png
description: >
  Data Engineer | Senior DBA
  Transforming Complex Data into Actionable Insights
  <br><br>
  Hi, I’m **Pravin Regismond**. I work with data—processing it, storing it, and making it useful. I started my career in database administration and spent over two decades managing and optimizing systems. More recently, I’ve been focusing on **data engineering**, working with **ETL pipelines, cloud platforms, and real-time data processing**.
  <br><br>
  I like solving problems, automating processes, and continuously learning new technologies. My experience spans **SQL, Python, Snowflake, Apache Airflow, Kafka, and DevOps tools**.
  <br><br>
  Feel free to check out my projects here or connect with me below.
show_social_links: true
linkedin_username: pregismond
show_github_links: false
show_downloads: false
google_analytics: G-L2N2PEQGY5
theme: jekyll-theme-minimal