title: Pravin Regismond
logo: /assets/img/headshot_circle.png
description: Data Engineer | Senior DBA | Transforming Complex Data into Actionable Insights
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal