title: Pravin Regismond
logo: /assets/img/headshot_circle.png
description: >
  <strong>Data Engineer | Senior DBA</strong>
  <br>
  Building Cloud-Native, Scalable Data Platforms
  <br><br>
  Hi, I’m <strong>Pravin Regismond</strong>. I work with data—processing it, storing it, and making it useful. I started my career in database administration and spent over two decades managing and optimizing systems. More recently, I’ve been focusing on <strong>data engineering</strong>, working with <strong>ETL pipelines, cloud platforms, and real-time data processing</strong>.
  <br><br>
  Feel free to check out my projects here or connect with me below.
show_social_links: true
linkedin_username: pregismond
snowflake_directory: 0ff6d022-a3b2-482d-9908-28c3e67eeb32
show_github_links: false
show_downloads: false
google_analytics: G-L2N2PEQGY5
theme: jekyll-theme-minimal