title: Pravin Regismond
logo: /assets/img/headshot_circle.png
description: Data Engineer | Senior DBA | Transforming Complex Data into Actionable Insights
linkedin_username: pregismond
show_github_links: false
show_downloads: false
google_analytics: G-L2N2PEQGY5
theme: jekyll-theme-minimal